### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by oliweroleksuch** [raj-khare/yt-migrate#1]
Hi,
I have absolutely zero experience in programming but I really need to migrate my YouTube subscriptions. Could you help me with that? 
Thanks in advance,
Oliwer.

(I can delete this post later, I just didn't know how to contact you.)

**Comment by raj-khare** [comment]
Sure. Can you mail me at raj.11803163@lpu.in?

**Comment by raj-khare** [comment]
Hey! I tried contacting you. But you didn't respond.

**Comment by weldon1045** [comment]
I also need help too and with the last step specially, email me to cam4076056@outlook.com so we can stay in touch
