### ISSUE TITLE
Client Loading Failed, 

### ISSUE THREAD

**Issue by ChimeraMittens** [raj-khare/yt-migrate#14]
I have done all the steps and I use the google account that I will be transferring my subscription as the google cloud user with the keys and all.

**Comment by raj-khare** [comment]
Can you share the error message by going to dev console?

**Comment by nonokh** [comment]
i am getting the same error.

**Comment by ahmed2m** [comment]
For future reference this is caused because the client doesn't have access to Youtube API, so as the readme says in the first step  `enable YouTube Data API v3 under API & Services`
