### ISSUE TITLE
Quota reached

### ISSUE THREAD

**Issue by laspinacristian** [raj-khare/yt-migrate#2]
Hi @raj-khare,

First of all thank you for sharing this project.

I'm trying to transfer my subscriptions (~350) and as you expected i reach quota limit at about 100 requests.

Do you think i can complete the rest of subscriptions in the next days?

Thanks

**Comment by raj-khare** [comment]
Um.. the point is even if you run the script the next day, it will transfer already subscribed channels again and exhaust your quota. So I am making changes to the code so you will be able to do that just fine.

**Comment by raj-khare** [comment]
I've made some changes so you will be able to transfer all the remaining subscriptions the next day if the quota is exhausted.
Let me know if you face any difficulty.

**Comment by laspinacristian** [comment]
Hi raj,

Thank you for your response. I've seen the changes you've made and it should work as expected.

But to tell the truth i've modified your script to my liking, saving results from my old account to local storage so i don't waste request to retrieve data I already have. Then I put in a variable the index number from which the function transferSubscription should start subscribe

But it seems there is another limit introduced by YouTube API v3. Now the API respond with status 400 "Too many recent subscriptions. Try again in a few hours"
I'm now close to have all subscriptions transferred

Thanks for your brilliant solution :)
