### ISSUE TITLE
Need assistance for the html

### ISSUE THREAD

**Issue by weldon1045** [raj-khare/yt-migrate#3]
Hello, I'm in an urgency of migrating my suscriptions from one channel to another, Could that be possible?, I didn't understand last step.

**Comment by TroyNech** [comment]
Follow https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#Running_a_simple_local_HTTP_server. Though I get a 403 when trying to login to the second account.

**Comment by TroyNech** [comment]
Cloning evan reilly's original repo, substituting my API key and client ID, and serving on the correct port worked for me.

**Comment by raj-khare** [comment]
You can just open the index.html in the browser (default port 80)

**Comment by raj-khare** [comment]
> Cloning evan reilly's original repo, substituting my API key and client ID, and serving on the correct port worked for me. Though I am now getting an error for all of my subscriptions when trying to enable notifications that notifications are disabled because the channel "is for children". Possibly related to the quota, idk

Are you facing any problem in this code?

**Comment by TroyNech** [comment]
The "is for children" problem seems to be a problem with how Evan's code adds the subscriptions. Not sure if your code does it the same way or not. With your code I was getting a 403 when trying to login to the second (destination) account.

**Comment by raj-khare** [comment]
Maybe try a second time as the API key is not verified by google. It sometimes blocks the first request due to security but when you provide access confirmation in OAUTH screen, then it allows after some time.
