### ISSUE TITLE
Number of failed migrations increases

### ISSUE THREAD

**Issue by alexs77** [raj-khare/yt-migrate#8]
I was now finally able to migrate the majority of subscriptions. I tried again today, and it told me, that 3 out of 4 subs had been transferred and I might be out of quota.

Then I just clicked on "initiate transfer" again, and now it showed 3 out of 8 succeeded? Clicked once more, now 3 out of 12 and then 3 out of 16. I bet, if I'd click again, I'd get 3/20, 3/24, 3/28 and so on.

What's going on there?

![Youtube_Migrate 1](https://user-images.githubusercontent.com/781361/81042001-79140e80-8eaf-11ea-9faa-c5cce48a2186.png)
![Youtube_Migrate 2](https://user-images.githubusercontent.com/781361/81042000-79140e80-8eaf-11ea-8fa4-3f37c87a9f0c.png)
![Youtube_Migrate 3](https://user-images.githubusercontent.com/781361/81041999-787b7800-8eaf-11ea-8462-b62cd7799eff.png)
![Youtube_Migrate 4](https://user-images.githubusercontent.com/781361/81041996-774a4b00-8eaf-11ea-835c-05043d5c2197.png)

**Comment by raj-khare** [comment]
You have to start all over again after the quota exhaustion message. I’ll fix it by disabling the button.

**Comment by alexs77** [comment]
Ah, that's better.
Thanks :)
