### ISSUE TITLE
Maximum Amount of Subscriptions Exceeded (Do I need Quote Increase?)

### ISSUE THREAD

**Issue by aucoindan** [raj-khare/yt-migrate#9]
I am trying to transfer 228 subscriptions to a new account. I created a fresh gcloud account (i.e. no API calls yet). I was only able to transfer 86 accounts before my quota reached. I then created a new account to see if I could transfer any additional (new quota). However, I am reaching the quota before any subscriptions are transferred. 

Method name | Requests | Error %
youtube.subscriptions.insert | 397 | 35.77%
youtube.subscriptions.list | 8 | 12.5%

The app is making 13,387 queries in order to transfer these accounts, or 58 queries per subscription.

According to docs -  Subscriptions: insert
Quota impact: A call to this method has a quota cost of 50 units in addition to the costs of the specified resource parts.

Knowing that, we probably need to implement some filtering before inserting subscriptions. Because it appears that inserts are happening on subscriptions that have already been transferred. 

badRequest (400) | subscriptionDuplicate | The subscription that you are trying to create already exists.

**Comment by raj-khare** [comment]
```JS
for (let [id, name] of Object.entries(USER_DATA.oldSubscriptions)) {
    if (!(id in USER_DATA.currentSubscriptions)) {
      // Subscribe the new one
    } else {
      USER_DATA.alreadyInAccount[id] = name;
    }
  }
```
It appears that the code should only subscribe the new ones. But I'll have a look at why this strange (13,387 queries 🤯) case is happening.
